github:
  description: "Erlang API for FoundationDB"
  homepage: https://www.foundationdb.org
  labels:
    - couchdb
    - erlang
    - foundationdb
  features:
    issues: true
  enabled_merge_buttons:
    squash: true
    rebase: true
    merge: true

notifications:
    commits: commits@couchdb.apache.org
    issues: notifications@couchdb.apache.org
    pullrequests: notifications@couchdb.apache.org
